// English texts for “Vienna Days”. Order of people and stops matches js/data.js.
export default {
  heroes: {
    mozart: {
      short:"Mozart", name:"Wolfgang Amadeus Mozart", inVienna:"in Vienna from 1781 to 1791",
      date:"1 May 1786", dayTitle:"The day of the Figaro premiere",
      lede:"Mozart is thirty. He is the most fashionable pianist in Vienna, lives in the finest flat of his life, and tonight the court’s Burgtheater gives the first performance of his new opera, to a libretto by Lorenzo Da Ponte.",
      start:"Stephansplatz U-Bahn station (U1, U3), then a 3-minute walk to Domgasse.",
      epilogue:"A year later Mozart will move to a cheaper flat. Five years later, on 5 December 1791, he will die at Rauhensteingasse 8, five minutes from Domgasse.",
      stops:[
        {title:"The flat in Domgasse", short:"Domgasse 5", place:"Mozarthaus Vienna",
         voice:"Good morning! You are standing in the finest flat I have ever rented: four rooms, two small chambers and a kitchen, four hundred and sixty florins a year. Father thinks it madness. This is where I finished Figaro. Last winter my quartets were played in these rooms, and Herr Haydn told my father that I was the greatest composer he knew, in person or by name. One doesn’t forget that. And now a game of billiards, then into town.",
         src:"Reconstruction. Haydn’s words are recorded by Leopold Mozart in a letter to his daughter, 16 February 1785",
         fact:"Mozart lived here from autumn 1784 to spring 1787, longer than in any other of his Vienna flats. Here he wrote The Marriage of Figaro, several piano concertos and the quartets dedicated to Haydn. Billiards was his passion: the inventory made after his death lists a billiard table with balls and cues.",
         now:"The Mozarthaus Vienna museum. Of more than a dozen flats Mozart lived in in Vienna, this is the only one that survives."},
        {title:"St Stephen’s Cathedral", short:"Stephansdom", place:"Stephansdom",
         voice:"Two hundred steps and I am at the cathedral. Nearly four years ago, in August, I married Constanze here. Father’s blessing arrived only the next day. When we were joined together, my wife and I both began to weep, and everyone was moved, even the priest. I think of it every time I pass.",
         src:"After Mozart’s letter to his father, 7 August 1782",
         fact:"Mozart and Constanze Weber were married here on 4 August 1782. In 1791 Mozart became assistant to the cathedral’s Kapellmeister: unpaid, but with the right to succeed him. On 6 December 1791 his body was blessed in the Crucifix Chapel on the north side of the cathedral.",
         now:"The way down to the catacombs starts in the Crucifix Chapel. You can climb the South Tower on foot: 343 steps."},
        {title:"The Mehlgrube concert hall", short:"Mehlgrube", place:"Neuer Markt, on the site of the Mehlgrube casino",
         voice:"The Mehlgrube, the ‘flour pit’. Flour used to be stored here; now upstairs there is a hall for balls and concerts. Last winter I gave concerts here on Fridays. At the first one I played my new concerto in D minor. The copyist delivered the parts so late that I did not even have time to play the rondo through: I was busy checking the copying myself. My father had arrived in Vienna that very day and sat in the hall.",
         src:"After Leopold Mozart’s letter to his daughter, February 1785",
         fact:"On 11 February 1785 the Piano Concerto in D minor, K. 466, was heard for the first time at the Mehlgrube. The casino building has not survived; the Hotel Ambassador stands on its site.",
         now:"In the middle of the square is the Donner Fountain. Three minutes away is Café Frauenhuber (Himmelpfortgasse 6): in this building, on 4 March 1791, Mozart appeared in public as a pianist for the last time."},
        {title:"The Trattnerhof on the Graben", short:"Trattnerhof", place:"Trattnerhof",
         voice:"The Graben, the smartest street in town. Two years ago I lived here, in the house of the publisher Trattner. His wife Therese is my pupil; I dedicated the Fantasia and Sonata in C minor to her. In the hall of this house I gave subscription concerts, and I had a hundred and seventy-four subscribers: all of fashionable Vienna! I sent Father the whole list.",
         src:"After Mozart’s letter to his father, 20 March 1784",
         fact:"Mozart lived in the Trattnerhof from January to September 1784 and gave three subscription concerts here that spring. Johann Thomas von Trattner was the biggest publisher and printer in Vienna at the time. The present building dates from the early twentieth century and stands on the site of the old one.",
         now:"Nearby is the Plague Column, consecrated in 1693: Mozart saw it every day. Two minutes away is Café Hawelka in Dorotheergasse."},
        {title:"Artaria, the publishers", short:"Artaria", place:"Kohlmarkt",
         voice:"The Kohlmarkt, and Artaria’s shop. Last autumn they printed my six quartets with a dedication to Herr Haydn. I wrote to him that I was placing my six children in his care, the fruit of long and laborious toil. Let’s see how they are selling. Then on to the theatre: it is not long until evening.",
         src:"The quotation is from Mozart’s Italian dedication of the quartets to Haydn, 1 September 1785",
         fact:"Artaria & Comp. was Vienna’s leading music publisher in the late eighteenth century, printing works by Mozart, Haydn and later Beethoven. The present Artaria building at Kohlmarkt 9 was built by Max Fabiani in 1900–1902; it was the first house in Vienna with a marble façade.",
         now:"On the way to the square is the Demel confectioners (Kohlmarkt 14). Its story began in that same year, 1786, when the confectioner Ludwig Dehne opened a shop on Michaelerplatz, opposite the Burgtheater’s stage door."},
        {title:"Premiere at the Burgtheater", short:"Burgtheater", place:"Michaelerplatz, site of the old Burgtheater",
         voice:"Here it is, the Burgtheater, the court theatre two steps from the Emperor’s apartments. At the dress rehearsal Benucci sang “Non più andrai” with such fire that I kept repeating under my breath: “Bravo, bravo, Benucci!” Then the singers and the whole orchestra shouted: “Bravo, Maestro! Viva, viva, grande Mozart!”, and the violinists beat their bows on the music stands. Tonight I direct the orchestra myself from the keyboard. Wish me luck.",
         src:"After the reminiscences of the tenor Michael Kelly, the first Don Basilio (1826)",
         fact:"The Marriage of Figaro opened on 1 May 1786; Mozart directed the first two performances himself. Encores were demanded so often that after the third performance Joseph II banned repeats of numbers for more than one voice. Kelly remembered Mozart at the rehearsal in a crimson pelisse and a gold-laced cocked hat. The old Burgtheater was demolished in 1888, when the new theatre on the Ring opened.",
         now:"Where the theatre stood is now the Michaelertrakt wing of the Hofburg with the Michaeler Gate. In the middle of the square are open excavations of Roman and medieval buildings. Figaro is regularly performed at the Vienna State Opera, ten minutes from here."}
      ]
    },
    beethoven: {
      short:"Beethoven", name:"Ludwig van Beethoven", inVienna:"in Vienna from 1792 until his death",
      date:"6 October 1802", dayTitle:"Heiligenstadt: the day of the Testament",
      lede:"Beethoven is thirty-one. Vienna knows him as its finest improviser at the piano, but for several years he has been losing his hearing and hiding it from everyone. On his doctor’s advice he has spent the summer in the wine village of Heiligenstadt. Today he will write his brothers a letter that will be found only after his death.",
      start:"About a 20-minute walk from Heiligenstadt U4 station.",
      epilogue:"Beethoven will live another twenty-five years and write the Ninth Symphony when already completely deaf. He died in Vienna on 26 March 1827.",
      stops:[
        {title:"The house in Heiligenstadt", short:"Probusgasse 6", place:"Beethoven Museum (Wien Museum)",
         voice:"It is quiet here. Too quiet, and it is not the village. Doctor Schmidt told me to spare my hearing, and I obeyed: for half a year I have hardly spoken to anyone. People think I am proud and misanthropic. And I cannot say to them: speak louder, shout, for I am deaf. Ah, how could I possibly admit to a weakness in the one sense that ought to be more perfect in me than in others?",
         src:"After the Heiligenstadt Testament, 6 October 1802",
         fact:"From spring to October 1802 Beethoven rented rooms here on the advice of his doctor, Johann Adam Schmidt. On 6 October he wrote to his brothers Carl and Johann the letter known as the Heiligenstadt Testament, adding a postscript on 10 October. It was never sent; it was found among his papers after his death in 1827.",
         now:"The Beethoven Museum, a branch of Wien Museum, in the house where he lived in 1802. The original Testament is kept in Hamburg, at the State and University Library."},
        {title:"The square by St James’s Church", short:"Pfarrplatz", place:"Pfarrplatz and St Jakob church",
         voice:"October, and the village is bringing in the grapes. I nod to the neighbours and walk on: every conversation is torture. My ears hum and roar day and night. I wrote to my friend in Bonn: at the theatre I have to sit right by the orchestra to understand the actors, and from a distance I cannot hear the high notes of instruments or voices at all.",
         src:"After Beethoven’s letter to Franz Wegeler, 29 June 1801",
         fact:"The letter to his childhood friend Wegeler is Beethoven’s first known admission of his deafness: “for almost two years I have avoided all social gatherings, because I cannot bring myself to tell people: I am deaf.” Beethoven lived in the house at Pfarrplatz 2 later, in the summer of 1817.",
         now:"No. 2 houses a winery and the Mayer am Pfarrplatz heuriger: you can drink the new wine where Beethoven spent the summer of 1817."},
        {title:"A walk to the vineyards", short:"Eroicagasse", place:"Eroicagasse, the way to the Beethovengang",
         voice:"I am walking across the fields with Ries, my pupil. Suddenly he stops: “Can you hear? A shepherd is playing his pipe.” I listen, for a long time, and nothing. Ries says he can’t hear it any more either, but I can see he says it out of pity. What humiliation. Such moments brought me close to despair; a little more, and I would have ended my own life.",
         src:"After the recollections of Ferdinand Ries (1838) and the text of the Testament",
         fact:"The scene was described by Ferdinand Ries: a shepherd was playing a pipe, Beethoven could hear nothing for half an hour and afterwards became extremely quiet and gloomy. Historians allow that Ries, writing decades later, may have blended his memory with the Testament, where Beethoven describes the same scene in his own words.",
         now:"Eroicagasse climbs to the Beethovengang path. It is named after the Third Symphony, the Eroica; in the summer of 1803 Beethoven worked on it in the house at Döblinger Hauptstraße 92."},
        {title:"The path along the brook", short:"Beethovengang", place:"Beethovengang, the Beethovenruhe monument",
         voice:"I go down to the brook. Here I have nothing to explain to anyone; the trees don’t ask to be heard. No one can love the countryside as much as I do. For woods, trees and rocks give back the echo that man desires.",
         src:"The last two sentences are from Beethoven’s letter to Therese Malfatti, 1810",
         fact:"Beethoven loved the path along the Schreiberbach. Tradition has it that the ‘Scene by the brook’ of the Sixth Symphony, the Pastoral (1808), was later conceived here; the story goes back to his secretary Anton Schindler, not always a reliable source. In 1863 a bronze bust by Anton Dominik Fernkorn was unveiled beside the path, the first Beethoven monument in the Vienna area.",
         now:"The Beethovenruhe monument stands by the brook, near Kahlenberger Straße. From here you can climb to the Kahlenberg on city hiking trail no. 1."},
        {title:"The letter to his brothers", short:"Probusgasse 6", place:"Back at the house in Probusgasse",
         voice:"O you men who think or say that I am hostile, obstinate or misanthropic, how greatly you wrong me! You do not know the secret cause of what seems so to you. Only art, only art held me back. Ah, it seemed impossible to me to leave the world before I had brought forth all that I felt called to do. Heiligenstadt, the 6th of October 1802.",
         src:"Heiligenstadt Testament, 6 October 1802 (excerpts in translation)",
         fact:"A few weeks later Beethoven will return to Vienna and start the Third Symphony. It is usually taken as the beginning of his ‘heroic’ period: the Fifth Symphony, the opera Fidelio, the Violin Concerto.",
         now:"The museum’s exhibition tells the story of the Testament and of how Beethoven lived with his deafness."}
      ]
    },
    klimt: {
      short:"Klimt", name:"Gustav Klimt", inVienna:"lived in Vienna all his life",
      date:"Spring 1908", dayTitle:"Breakfast at the Tivoli, a day in the studio",
      lede:"Klimt is forty-five. Three years ago he and his friends left the Secession he himself had founded. Now he is preparing the Kunstschau, a large exhibition in pavilions by Josef Hoffmann, where he will show for the first time the painting that will later be called The Kiss.",
      start:"About a 10-minute walk from Zieglergasse U3 station.",
      epilogue:"Klimt died on 6 February 1918. That same year Egon Schiele, Otto Wagner and Koloman Moser died too, and by autumn the Habsburg empire had come to an end.",
      stops:[
        {title:"The house he shared with his mother", short:"Westbahnstraße", place:"Apartment building in Neubau",
         voice:"I get up early. I live with my mother and sisters; it has always been that way. I cannot talk about myself and do not like to. There is nothing special to see in me. Whoever wants to know something about me as an artist, the only thing worth knowing, should look carefully at my pictures.",
         src:"After Klimt’s text “Commentary on a non-existent self-portrait”",
         fact:"Klimt lived here until his death with his mother Anna (she died in 1915) and his unmarried sisters Klara and Hermine. He never married; the person closest to him all his life was Emilie Flöge.",
         now:"An apartment building with a memorial plaque to Klimt, unveiled in 2001. The Tivoli is about an hour’s walk from here."},
        {title:"Breakfast at the Tivoli", short:"Tivoli", place:"Former Tivoli establishment in Meidling, between Hohenbergstraße, Tivoligasse and Grünbergstraße",
         go:"U4 to Schönbrunn or Meidling Hauptstraße, then about 15 minutes uphill on foot. Klimt walked or took the Stadtbahn, on the same line as today’s U4.",
         voice:"Every morning I walk to the Tivoli, by the Schönbrunn park. Sometimes I take the new city railway to Schönbrunn station. Everything here is like old Vienna, and I like that. Breakfast must be hearty, with whipped cream: until evening, while I work, I eat almost nothing.",
         src:"Reconstruction based on the recollections of contemporaries",
         fact:"The Tivoli pleasure garden and dairy on the Grüner Berg was one of Klimt’s favourite places; Egon Schiele came here too. A lavish breakfast with a large helping of whipped cream was part of Klimt’s daily ritual. Schönbrunn station, like the whole Stadtbahn, was designed by Otto Wagner.",
         now:"The Tivoli’s main building burned in 1980 and was demolished; housing estates stand on the site, among them the protected Am Tivoli estate. Close by are the Schönbrunn park and the café in the Gloriette, with a view over the city."},
        {title:"The garden studio", short:"Studio", place:"Courtyard of a house on Josefstädter Straße",
         go:"About 35 minutes by public transport; for the last stretch take tram 2, which runs right along Josefstädter Straße.",
         voice:"The studio is at the back of the courtyard, in the garden. Cats, silence, my blue smock. The models come in the morning and wait for hours until I start work. On the easel is a large square painting: two people on a flowering meadow, gold and silver. I don’t yet know what to call it.",
         src:"Reconstruction",
         fact:"Klimt worked here from 1892 to 1911, in a garden pavilion in the courtyard of a house built in 1709. In this studio he painted the Portrait of Adele Bloch-Bauer I and The Kiss (1907–1908). Later he moved to a studio in Hietzing, at Feldmühlgasse 11.",
         now:"A residential courtyard in Josefstadt. Klimt’s last studio can be visited: today it is the Klimt Villa museum in Hietzing."},
        {title:"The Flöge sisters’ salon", short:"Casa Piccola", place:"Casa Piccola building, opposite the MuseumsQuartier",
         voice:"I drop in on Emilie. Her fashion salon was furnished by the Wiener Werkstätte: white and black, not one unnecessary flourish. The dresses there are loose, without corsets, like in my paintings. In summer we will go to the Attersee with the Flöge family again. Until then I write her postcards, sometimes several a day.",
         src:"Reconstruction. Some 400 postcards and letters from Klimt to Emilie Flöge survive",
         fact:"The Schwestern Flöge salon of Emilie and her sisters Helene and Pauline operated in this building from 1904 to 1938; the interior was designed by Josef Hoffmann and Koloman Moser. Klimt photographed Emilie in loose ‘reform’ dresses; some of the designs may have been their joint work.",
         now:"The building with the pointed turret on Mariahilfer Straße, opposite the side entrance of the MuseumsQuartier. The salon is long gone."},
        {title:"The Secession building", short:"Secession", place:"Secession",
         voice:"I never pass the Secession without emotion. Above the entrance, golden leaves and the motto: “To every age its art, to art its freedom.” We built this house as a temple of the new art. In 1902 I painted a frieze here on Beethoven’s Ninth Symphony. And in 1905 I left, together with my friends.",
         src:"Reconstruction. The motto above the entrance is by the critic Ludwig Hevesi",
         fact:"The building was designed by Joseph Maria Olbrich in 1898. Klimt created the Beethoven Frieze for the 14th Secession exhibition in 1902; today it is shown in the basement. In 1905 the ‘Klimt group’ left the association after a split.",
         now:"The Secession exhibition hall is open, and the Beethoven Frieze can be seen inside."},
        {title:"Café Museum", short:"Café Museum", place:"Café Museum",
         voice:"In the evening, Café Museum. Loos made it severe and bare, without a single ornament; the wits call it ‘Café Nihilism’. Loos can’t stand ornament, and I live by it. But the coffee is good, and all our friends are here.",
         src:"Reconstruction",
         fact:"The café opened in 1899 with an interior by Adolf Loos. Its regulars are said to have included Klimt, Egon Schiele, Oskar Kokoschka and Loos himself.",
         now:"The café is still open today, two minutes from the Secession."},
        {title:"The Kunstschau building site", short:"Kunstschau", place:"Vienna Konzerthaus, on the site of the 1908 exhibition",
         voice:"Last of all I go to look at the building site. Hoffmann is putting up the pavilions for our Kunstschau: fifty-four rooms. This is our great statement, everything we can do, from posters to gardens. Let’s see what Vienna says.",
         src:"Reconstruction",
         fact:"The Kunstschau opened on 1 June 1908 on the plot where the Konzerthaus was later built. The Klimt room showed The Lovers, known today as The Kiss. The state bought it during the exhibition for the Modern Gallery; today it hangs in the Belvedere.",
         now:"The Konzerthaus opened in 1913. The Kiss hangs in the Upper Belvedere, about a 20-minute walk south."}
      ]
    },
    freud: {
      short:"Freud", name:"Sigmund Freud", inVienna:"in Vienna from 1860 to 1938",
      date:"A Wednesday in 1907", dayTitle:"Consulting room, the Ring and the Wednesday circle",
      lede:"Freud is fifty-one. The Interpretation of Dreams came out seven years ago and is selling slowly, and his Viennese colleagues scoff, but a circle of followers has already formed around him. Every Wednesday evening they argue about the unconscious in his flat in Berggasse.",
      start:"Tram D to Schlickgasse or U2 to Schottentor, then a 5-minute walk.",
      epilogue:"Freud died in London on 23 September 1939. Four of his sisters, who had stayed in Vienna, were murdered in the Holocaust.",
      stops:[
        {title:"Berggasse 19", short:"Berggasse 19", place:"Sigmund Freud Museum",
         voice:"Seven in the morning. Every day the barber comes to trim my beard. Breakfast, the newspaper, and at eight the first patient. The couch against the wall; I sit behind its head so the patient cannot see me. He says everything that comes into his mind, even if it seems trivial or improper. I listen. That is my work.",
         src:"Reconstruction based on Ernest Jones’s biography and Martin Freud’s memoirs",
         fact:"Freud lived and saw patients in this building for 47 years, from 1891 to June 1938. His routine hardly changed: patients from eight until noon, lunch at one sharp, a walk, patients again from three until nine in the evening, and after supper his desk, often until one in the morning.",
         now:"The Sigmund Freud Museum: waiting room, consulting room and private flat. The famous couch went with him into exile and is now in London, at the Freud Museum."},
        {title:"A march around the Ring", short:"Schottentor", place:"Schottentor and the Votivkirche",
         voice:"After lunch I go out onto the Ring. My son says it is not a stroll but a march: I walk at a terrific speed. On the way, the tobacconist. Twenty cigars a day; the doctors disapprove. But I owe to the cigar a great intensification of my capacity to work and a facilitation of my self-control.",
         src:"The words about the ‘march’ are Martin Freud’s; the sentence about the cigar gives Freud’s own words",
         fact:"The Ringstraße, about 5 km long, was laid out where the demolished city walls had stood; it was being built throughout Freud’s childhood and youth. Almost every day he walked it at a brisk pace, buying cigars and taking proofs to his publisher on the way.",
         now:"The Votivkirche was consecrated in 1879. From here, follow the Ring south to the university."},
        {title:"The university", short:"University", place:"Main building of the University of Vienna",
         voice:"The university. As a young man I used to walk around the Arcade Court among the busts of famous professors and imagine my own bust there, with a line from Oedipus Rex: he who divined the famed riddle and was a man most mighty. Last year my followers gave me a medallion for my fiftieth birthday with that very line. I turned pale, as if I had met a ghost.",
         src:"After Ernest Jones’s biography",
         fact:"Freud became a Privatdozent in 1885 but a professor only in 1902, seventeen years later. In 1955 his bust, bearing that very line from Sophocles, was placed in the Arcade Court. For the ceiling of the university’s Great Hall Gustav Klimt painted the ‘Faculty Paintings’; Philosophy (1900) and Medicine (1901) caused a huge scandal.",
         now:"The Arcade Court is open to visitors; Freud’s bust stands among those of the professors."},
        {title:"Café Landtmann", short:"Landtmann", place:"Café Landtmann in the Palais Lieben-Auspitz",
         voice:"Past the Burgtheater, past Café Landtmann. No time for coffee today: at three the patients come again. But on Saturday evening there will be tarock with friends, and at cards I am never in a hurry.",
         src:"Reconstruction",
         fact:"Café Landtmann opened in 1873 and counts Freud among its famous guests. Tarock, the Viennese card game, was Freud’s regular Saturday pastime for many years.",
         now:"The café is open. Opposite is the City Hall, next door the Burgtheater."},
        {title:"The Sühnhaus, the ‘House of Atonement’", short:"Sühnhaus", place:"Site of the Sühnhaus on the Schottenring, between Heßgasse and Maria-Theresien-Straße",
         voice:"On the way back, the Sühnhaus, the House of Atonement. The Emperor had it built on the site of the Ringtheater, where hundreds of spectators died in a fire in December 1881. Martha and I moved in here after our wedding. Our Mathilde was the first child born in this house, and the Emperor congratulated us on her birth.",
         src:"After Ernest Jones’s biography",
         fact:"The Freuds lived in the Sühnhaus from 1886 to 1891; their three eldest children were born here. The building was badly damaged in 1945 and demolished in 1951. The present police building went up in 1969–1971.",
         now:"On the façade of the police building a plaque from 1982 commemorates the victims of the Ringtheater fire and the Sühnhaus. Berggasse is about a 7-minute walk from here."},
        {title:"Wednesday evening", short:"Berggasse 19", place:"The waiting room at Berggasse 19",
         voice:"Patients until nine, then supper. And today is Wednesday: colleagues gather in the waiting room. Black coffee, cakes, cigars. The order of speakers is decided by lots drawn from an urn, and everyone must speak. When they have all gone, I will sit down at my desk. One in the morning is still a long way off.",
         src:"Reconstruction based on memoirs of members of the Wednesday Psychological Society",
         fact:"The Wednesday Psychological Society met in this flat from 1902; in 1908 it became the Vienna Psychoanalytic Society. In June 1938, after the Anschluss, the 82-year-old Freud emigrated with his family to London. In December 1938 the BBC recorded his voice: the only known recording of Freud speaking.",
         now:"The waiting room where the meetings took place still has its original furniture: Anna Freud returned it to the museum."}
      ]
    }
  },
  upcoming: {
    strauss:{short:"Strauss", name:"Johann Strauss II", teaser:"Praterstraße 54: the flat where the waltz On the Beautiful Blue Danube was written in 1867."},
    elssler:{short:"Elssler", name:"Fanny Elssler", teaser:"The girl from Gumpendorf, a debut at the Kärntnertor Theatre, then Paris, London and a tour of America."},
    mahler:{short:"Mahler", name:"Gustav Mahler", teaser:"Ten years at the head of the Court Opera: he dimmed the house lights and kept latecomers out."},
    lamarr:{short:"Lamarr", name:"Hedy Lamarr", teaser:"Born in Vienna, she became a Hollywood star and patented frequency hopping."},
    welles:{short:"Welles", name:"Orson Welles", teaser:"A few days in the autumn of 1948 filming The Third Man: the Ferris wheel, the sewers, Josefsplatz."}
  },
  links: [
    {title:"Mozart’s spirit from Haydn’s hands", text:"A year after Mozart’s death Beethoven leaves Bonn for Vienna. Count Waldstein writes in his album: “Through uninterrupted diligence you will receive Mozart’s spirit from Haydn’s hands.”"},
    {title:"A scandal on the ceiling", text:"Klimt shows Philosophy, the first of his paintings for the university ceiling, and it causes a scandal. A few months earlier Freud’s Interpretation of Dreams came out, with the date 1900 on its title page."},
    {title:"The Beethoven Frieze", text:"Klimt paints his frieze on the Ninth Symphony for the Secession’s exhibition in honour of Beethoven. At the opening a passage from the symphony is performed in an arrangement by Gustav Mahler."}
  ],
  how: [
    ["Navigation","Geofences, not buttons","Start the walk and the app follows your location. As you approach a place, the person’s voice starts by itself, and between stops you see the distance to the next one."],
    ["Sound","The person’s voice","The monologues are drawn from letters, diaries and memoirs. For now your phone’s speech synthesis reads them; next come recordings by actors and, for Freud, the real BBC recording from 1938."],
    ["Immersion","Moments on site","Short sound scenes: Beethoven’s hearing in 1802 is already here. Next: the Figaro rehearsal and the façade of the demolished Burgtheater laid over today’s Michaelerplatz."],
    ["Sources","Document or reconstruction","Under every monologue you can see where it comes from: a letter, a memoir, or a dramatised reconstruction. The historical notes are kept separate from the person’s voice."],
    ["Languages","Six languages, offline","The app speaks English, German, French, Italian, Spanish and Russian. After the first visit it is stored on your phone and works without mobile data."],
    ["Formats","One or two days","A short day of 2–3 hours or a two-day route: for example Beethoven in Heiligenstadt plus the evening of the Fifth Symphony’s premiere at the Theater an der Wien, 22 December 1808."]
  ]
};
