// Textos en español de «Días de Viena». El orden de personajes y paradas coincide con js/data.js.
export default {
  heroes: {
    mozart: {
      short:"Mozart", name:"Wolfgang Amadeus Mozart", inVienna:"en Viena de 1781 a 1791",
      date:"1 de mayo de 1786", dayTitle:"El día del estreno de Las bodas de Fígaro",
      lede:"Mozart tiene treinta años. Es el pianista más de moda de Viena, vive en el mejor piso de su vida y esta noche el Burgtheater, el teatro de la corte, estrena su nueva ópera con libreto de Lorenzo Da Ponte.",
      start:"Metro Stephansplatz (U1, U3), y desde allí 3 minutos a pie hasta la Domgasse.",
      epilogue:"Un año después Mozart se mudará a un piso más barato. Cinco años después, el 5 de diciembre de 1791, morirá en la Rauhensteingasse 8, a cinco minutos de la Domgasse.",
      stops:[
        {title:"El piso de la Domgasse", short:"Domgasse 5", place:"Mozarthaus Vienna",
         voice:"¡Buenos días! Está usted en el mejor piso que he alquilado nunca: cuatro habitaciones, dos gabinetes y una cocina, cuatrocientos sesenta florines al año. Mi padre lo considera una locura. Aquí terminé el Fígaro. El invierno pasado se tocaron mis cuartetos en estas salas, y el señor Haydn le dijo a mi padre que soy el mayor compositor que conoce, en persona o de nombre. Eso no se olvida. Y ahora una partida de billar, y a la ciudad.",
         src:"Reconstrucción. Las palabras de Haydn las recoge Leopold Mozart en una carta a su hija, 16 de febrero de 1785",
         fact:"Mozart vivió aquí desde el otoño de 1784 hasta la primavera de 1787, más tiempo que en ninguna otra de sus viviendas vienesas. Aquí escribió Las bodas de Fígaro, varios conciertos para piano y los cuartetos dedicados a Haydn. El billar era su pasión: el inventario hecho tras su muerte incluye una mesa de billar con bolas y tacos.",
         now:"El museo Mozarthaus Vienna. De la docena larga de pisos vieneses de Mozart, es el único que se conserva."},
        {title:"La catedral de San Esteban", short:"Stephansdom", place:"Stephansdom",
         voice:"Doscientos pasos y estoy en la catedral. Aquí, hace casi cuatro años, en agosto, me casé con Constanze. La bendición de mi padre llegó solo al día siguiente. Cuando nos unieron, mi mujer y yo nos echamos a llorar, y todos se conmovieron, hasta el sacerdote. Lo recuerdo cada vez que paso por aquí.",
         src:"Según la carta de Mozart a su padre, 7 de agosto de 1782",
         fact:"Mozart y Constanze Weber se casaron aquí el 4 de agosto de 1782. En 1791 Mozart fue nombrado adjunto del maestro de capilla de la catedral: sin sueldo, pero con derecho a sucederle. El 6 de diciembre de 1791 su cuerpo fue bendecido en la capilla del Crucifijo, en el costado norte de la catedral.",
         now:"Desde la capilla del Crucifijo se baja a las catacumbas. A la torre sur se sube a pie: 343 escalones."},
        {title:"La sala de conciertos de la Mehlgrube", short:"Mehlgrube", place:"Neuer Markt, donde estaba el casino de la Mehlgrube",
         voice:"La Mehlgrube, la «fosa de la harina». Antes aquí se guardaba harina; ahora arriba hay una sala para bailes y conciertos. El invierno pasado di aquí conciertos los viernes. En el primero toqué mi nuevo concierto en re menor. El copista entregó las partes tan tarde que ni siquiera pude ensayar el rondó: yo mismo vigilaba las copias. Mi padre había llegado a Viena ese mismo día y estaba en la sala.",
         src:"Según la carta de Leopold Mozart a su hija, febrero de 1785",
         fact:"El 11 de febrero de 1785 sonó por primera vez en la Mehlgrube el Concierto para piano en re menor K. 466. El edificio del casino no se conserva; en su lugar está el hotel Ambassador.",
         now:"En el centro de la plaza, la fuente de Donner. A tres minutos, el Café Frauenhuber (Himmelpfortgasse 6): en esta casa, el 4 de marzo de 1791, Mozart actuó en público como pianista por última vez."},
        {title:"El Trattnerhof en el Graben", short:"Trattnerhof", place:"Trattnerhof",
         voice:"El Graben, la calle más elegante de la ciudad. Hace dos años vivía aquí, en casa del editor Trattner. Su mujer, Therese, es mi alumna; le dediqué la Fantasía y la Sonata en do menor. En la sala de esta casa di conciertos por suscripción, y tuve ciento setenta y cuatro suscriptores: ¡toda la Viena distinguida! A mi padre le mandé la lista completa.",
         src:"Según la carta de Mozart a su padre, 20 de marzo de 1784",
         fact:"Mozart vivió en el Trattnerhof de enero a septiembre de 1784 y en primavera dio aquí tres conciertos por suscripción. Johann Thomas von Trattner era entonces el mayor editor e impresor de Viena. El edificio actual es de principios del siglo XX y ocupa el lugar del antiguo.",
         now:"Cerca está la Columna de la Peste, consagrada en 1693: Mozart la veía todos los días. A dos minutos, el Café Hawelka en la Dorotheergasse."},
        {title:"La editorial Artaria", short:"Artaria", place:"Kohlmarkt",
         voice:"El Kohlmarkt, la tienda de Artaria. El otoño pasado imprimieron mis seis cuartetos con la dedicatoria al señor Haydn. Le escribí que ponía bajo su protección a mis seis hijos, fruto de un largo y laborioso esfuerzo. Veamos cómo se venden. Luego, al teatro: falta poco para la noche.",
         src:"La cita procede de la dedicatoria en italiano de los cuartetos a Haydn, 1 de septiembre de 1785",
         fact:"Artaria & Comp. era la principal editorial musical de Viena a finales del siglo XVIII: publicaba a Mozart, a Haydn y más tarde a Beethoven. La actual casa Artaria, en el Kohlmarkt 9, la construyó Max Fabiani en 1900–1902; fue la primera casa de Viena con fachada de mármol.",
         now:"De camino a la plaza está la confitería Demel (Kohlmarkt 14). Su historia empezó ese mismo año, 1786, cuando el confitero Ludwig Dehne abrió una tienda en la Michaelerplatz, frente a la entrada de artistas del Burgtheater."},
        {title:"Estreno en el Burgtheater", short:"Burgtheater", place:"Michaelerplatz, donde estaba el antiguo Burgtheater",
         voice:"Aquí está el Burgtheater, el teatro de la corte, a dos pasos de los aposentos del emperador. En el ensayo general Benucci cantó «Non più andrai» con tanto fuego que yo repetía a media voz: «¡Bravo, bravo, Benucci!» Y entonces los cantantes y toda la orquesta gritaron: «¡Bravo, Maestro! ¡Viva, viva, grande Mozart!», y los violinistas golpeaban los atriles con los arcos. Esta noche dirijo yo mismo la orquesta desde el teclado. Deséenme suerte.",
         src:"Según las memorias del tenor Michael Kelly, el primer Don Basilio (1826)",
         fact:"Las bodas de Fígaro se estrenaron el 1 de mayo de 1786; Mozart dirigió en persona las dos primeras funciones. Se pedían tantos bises que, tras la tercera función, José II prohibió repetir los números para más de una voz. Kelly recordaba a Mozart en el ensayo con una pelliza carmesí y un tricornio con galón dorado. El antiguo Burgtheater fue derribado en 1888, cuando se inauguró el nuevo teatro del Ring.",
         now:"Donde estaba el teatro se alza hoy el ala Michaelertrakt del Hofburg con la puerta de San Miguel. En medio de la plaza hay excavaciones abiertas de edificios romanos y medievales. Las bodas de Fígaro se representan con regularidad en la Ópera Estatal de Viena, a diez minutos de aquí."}
      ]
    },
    beethoven: {
      short:"Beethoven", name:"Ludwig van Beethoven", inVienna:"en Viena desde 1792 hasta su muerte",
      date:"6 de octubre de 1802", dayTitle:"Heiligenstadt: el día del Testamento",
      lede:"Beethoven tiene treinta y un años. Viena lo conoce como el mejor improvisador al piano, pero desde hace varios años está perdiendo el oído y lo oculta a todos. Por consejo de su médico ha pasado el verano en el pueblo vinícola de Heiligenstadt. Hoy escribirá a sus hermanos una carta que solo se encontrará después de su muerte.",
      start:"A unos 20 minutos a pie de la estación U4 Heiligenstadt.",
      epilogue:"Beethoven vivirá veinticinco años más y escribirá la Novena Sinfonía ya completamente sordo. Murió en Viena el 26 de marzo de 1827.",
      stops:[
        {title:"La casa de Heiligenstadt", short:"Probusgasse 6", place:"Museo Beethoven (Wien Museum)",
         voice:"Aquí hay silencio. Demasiado silencio, y no es cosa del pueblo. El doctor Schmidt me ordenó cuidar el oído, y obedecí: hace medio año que casi no hablo con nadie. La gente me cree soberbio y misántropo. Y no puedo decirles: hablad más alto, gritad, porque estoy sordo. ¿Cómo confesar la debilidad de un sentido que en mí debería ser más perfecto que en los demás?",
         src:"Según el Testamento de Heiligenstadt, 6 de octubre de 1802",
         fact:"De la primavera a octubre de 1802 Beethoven alquiló aquí una vivienda por consejo de su médico, Johann Adam Schmidt. El 6 de octubre escribió a sus hermanos Carl y Johann la carta conocida como Testamento de Heiligenstadt, y el 10 de octubre añadió una posdata. Nunca la envió: se encontró entre sus papeles tras su muerte, en 1827.",
         now:"El Museo Beethoven, sede del Wien Museum, en la casa donde vivió en 1802. El original del Testamento se guarda en Hamburgo, en la Biblioteca Estatal y Universitaria."},
        {title:"La plaza de la iglesia de Santiago", short:"Pfarrplatz", place:"Pfarrplatz e iglesia de St. Jakob",
         voice:"Octubre, en el pueblo es la vendimia. Saludo a los vecinos con la cabeza y sigo andando: cada conversación es una tortura. Los oídos me zumban y retumban día y noche. A mi amigo de Bonn le escribí: en el teatro tengo que sentarme pegado a la orquesta para entender a los actores, y de lejos no oigo en absoluto los agudos de los instrumentos ni de las voces.",
         src:"Según la carta de Beethoven a Franz Wegeler, 29 de junio de 1801",
         fact:"La carta a su amigo de la infancia Wegeler es la primera confesión conocida de su sordera: «desde hace casi dos años evito toda compañía, porque no me es posible decir a la gente: estoy sordo». En la casa de Pfarrplatz 2 vivió Beethoven más tarde, en el verano de 1817.",
         now:"En el número 2 hay una bodega y el Heuriger Mayer am Pfarrplatz: se puede beber el vino nuevo donde Beethoven pasó el verano de 1817."},
        {title:"Paseo hacia los viñedos", short:"Eroicagasse", place:"Eroicagasse, camino del Beethovengang",
         voice:"Cruzo los campos con Ries, mi alumno. De pronto se detiene: «¿Lo oye? Un pastor toca la flauta». Escucho, largo rato, y nada. Ries dice que él tampoco lo oye ya, pero veo que lo dice por compasión. Qué humillación. Momentos así me llevaron al borde de la desesperación; poco faltó para que yo mismo pusiera fin a mi vida.",
         src:"Según los recuerdos de Ferdinand Ries (1838) y el texto del Testamento",
         fact:"La escena la contó Ferdinand Ries: un pastor tocaba la flauta, Beethoven no oyó nada durante media hora y después se quedó muy callado y sombrío. Los historiadores admiten que Ries, que escribió décadas más tarde, pudo mezclar su recuerdo con el texto del Testamento, donde Beethoven describe la misma escena con sus propias palabras.",
         now:"La Eroicagasse sube hacia el sendero Beethovengang. Debe su nombre a la Tercera Sinfonía, la «Heroica»; en el verano de 1803 Beethoven trabajó en ella en la casa de Döblinger Hauptstraße 92."},
        {title:"El sendero junto al arroyo", short:"Beethovengang", place:"Beethovengang, monumento «Beethovenruhe»",
         voice:"Bajo al arroyo. Aquí no tengo que explicar nada a nadie; los árboles no exigen que se les oiga. Nadie puede amar el campo tanto como yo. Porque los bosques, los árboles y las rocas devuelven el eco que el hombre desea.",
         src:"Las dos últimas frases proceden de la carta de Beethoven a Therese Malfatti, 1810",
         fact:"A Beethoven le encantaba el camino junto al Schreiberbach. Según la tradición, aquí nació más tarde la «Escena junto al arroyo» de la Sexta Sinfonía, la «Pastoral» (1808); la historia se remonta a su secretario Anton Schindler, fuente no siempre fiable. En 1863 se inauguró junto al sendero un busto de bronce de Anton Dominik Fernkorn, el primer monumento a Beethoven en los alrededores de Viena.",
         now:"El monumento «Beethovenruhe» está junto al arroyo, cerca de la Kahlenberger Straße. Desde aquí se puede subir al Kahlenberg por el sendero urbano n.º 1."},
        {title:"La carta a los hermanos", short:"Probusgasse 6", place:"De vuelta en la casa de la Probusgasse",
         voice:"¡Oh vosotros, hombres que me tenéis o me declaráis hostil, testarudo o misántropo, qué injustos sois conmigo! No conocéis la causa secreta de lo que os parece así. Solo el arte, solo él me retuvo. Ah, me parecía imposible dejar el mundo antes de haber creado todo aquello para lo que me sentía llamado. Heiligenstadt, 6 de octubre de 1802.",
         src:"Testamento de Heiligenstadt, 6 de octubre de 1802 (fragmentos traducidos)",
         fact:"Pocas semanas después Beethoven volverá a Viena y empezará la Tercera Sinfonía. Con ella suele comenzar su periodo «heroico»: la Quinta Sinfonía, la ópera Fidelio, el Concierto para violín.",
         now:"La exposición del museo cuenta la historia del Testamento y cómo vivió Beethoven con su sordera."}
      ]
    },
    klimt: {
      short:"Klimt", name:"Gustav Klimt", inVienna:"vivió toda su vida en Viena",
      date:"Primavera de 1908", dayTitle:"Desayuno en el Tivoli, un día en el taller",
      lede:"Klimt tiene cuarenta y cinco años. Hace tres años dejó con sus amigos la Secesión que él mismo había fundado. Ahora prepara la Kunstschau, una gran exposición en pabellones de Josef Hoffmann, donde mostrará por primera vez el cuadro que más tarde se llamará El beso.",
      start:"A unos 10 minutos a pie de la estación U3 Zieglergasse.",
      epilogue:"Klimt murió el 6 de febrero de 1918. Ese mismo año murieron Egon Schiele, Otto Wagner y Koloman Moser, y en otoño terminó también el imperio de los Habsburgo.",
      stops:[
        {title:"La casa donde vivía con su madre", short:"Westbahnstraße", place:"Edificio de viviendas en Neubau",
         voice:"Me levanto temprano. Vivo con mi madre y mis hermanas, siempre ha sido así. No sé hablar de mí mismo y no me gusta. En mí no hay nada especial que ver. Quien quiera saber algo de mí como artista, que es lo único que merece la pena, que mire con atención mis cuadros.",
         src:"Según el texto de Klimt «Comentario a un autorretrato inexistente»",
         fact:"Klimt vivió aquí hasta su muerte con su madre, Anna (murió en 1915), y sus hermanas solteras Klara y Hermine. Nunca se casó; la persona más cercana a él durante toda su vida fue Emilie Flöge.",
         now:"Un edificio de viviendas con una placa conmemorativa dedicada a Klimt, inaugurada en 2001. Hasta el Tivoli hay casi una hora a pie."},
        {title:"Desayuno en el Tivoli", short:"Tivoli", place:"Antiguo local Tivoli en Meidling, entre Hohenbergstraße, Tivoligasse y Grünbergstraße",
         go:"U4 hasta Schönbrunn o Meidling Hauptstraße y luego unos 15 minutos a pie cuesta arriba. Klimt iba andando o en el Stadtbahn, por la misma línea que hoy recorre la U4.",
         voice:"Cada mañana camino hasta el Tivoli, junto al parque de Schönbrunn. A veces tomo el nuevo ferrocarril urbano hasta la estación de Schönbrunn. Aquí todo es como en la vieja Viena, y eso me gusta. El desayuno tiene que ser contundente, con nata montada: hasta la noche, mientras trabajo, casi no como nada.",
         src:"Reconstrucción a partir de los recuerdos de contemporáneos",
         fact:"El local de recreo y lechería Tivoli, en el Grüner Berg, era uno de los lugares favoritos de Klimt; también venía Egon Schiele. Un desayuno copioso con una gran ración de nata montada formaba parte de su ritual diario. La estación de Schönbrunn, como todo el Stadtbahn, la diseñó Otto Wagner.",
         now:"El edificio principal del Tivoli ardió en 1980 y fue derribado; en su lugar hay conjuntos de viviendas, entre ellos la colonia protegida «Am Tivoli». Cerca están el parque de Schönbrunn y el café de la Gloriette, con vistas a la ciudad."},
        {title:"El taller en el jardín", short:"Taller", place:"Patio de una casa de la Josefstädter Straße",
         go:"Unos 35 minutos en transporte público; el último tramo conviene hacerlo en el tranvía 2, que pasa justo por la Josefstädter Straße.",
         voice:"El taller está al fondo del patio, en el jardín. Gatos, silencio, mi bata azul. Las modelos llegan por la mañana y esperan horas hasta que me pongo a trabajar. En el caballete hay un gran cuadro cuadrado: dos personas en un prado en flor, oro y plata. Todavía no sé cómo llamarlo.",
         src:"Reconstrucción",
         fact:"Klimt trabajó aquí de 1892 a 1911, en un pabellón del jardín de una casa de 1709. En este taller pintó el Retrato de Adele Bloch-Bauer I y El beso (1907–1908). Más tarde se trasladó a un taller en Hietzing, en la Feldmühlgasse 11.",
         now:"Un patio de viviendas en la Josefstadt. El último taller de Klimt se puede visitar: hoy es el museo Klimt Villa, en Hietzing."},
        {title:"El salón de las hermanas Flöge", short:"Casa Piccola", place:"Casa Piccola, frente al MuseumsQuartier",
         voice:"Paso a ver a Emilie. Su salón de moda lo amuebló la Wiener Werkstätte: blanco y negro, ni una floritura de más. Los vestidos son amplios, sin corsé, como en mis cuadros. En verano volveremos al Attersee con la familia Flöge. Mientras tanto le escribo postales, a veces varias al día.",
         src:"Reconstrucción. Se conservan unas 400 postales y cartas de Klimt a Emilie Flöge",
         fact:"El salón «Schwestern Flöge» de Emilie y sus hermanas Helene y Pauline estuvo en esta casa de 1904 a 1938; el interior lo diseñaron Josef Hoffmann y Koloman Moser. Klimt fotografiaba a Emilie con amplios vestidos «reformistas»; quizá idearon juntos algunos modelos.",
         now:"La casa de la torrecilla puntiaguda en la Mariahilfer Straße, frente a la entrada lateral del MuseumsQuartier. El salón ya no existe."},
        {title:"El edificio de la Secesión", short:"Secesión", place:"Secession",
         voice:"Nunca paso por delante de la Secesión sin emoción. Sobre la entrada, follaje dorado y el lema: «A cada época su arte, al arte su libertad». Construimos esta casa como un templo del arte nuevo. En 1902 pinté aquí un friso sobre la Novena Sinfonía de Beethoven. Y en 1905 me fui con mis amigos.",
         src:"Reconstrucción. El lema sobre la entrada es del crítico Ludwig Hevesi",
         fact:"El edificio lo construyó Joseph Maria Olbrich en 1898. Klimt creó el Friso de Beethoven para la 14.ª exposición de la Secesión en 1902; hoy se muestra en el sótano. En 1905 el «grupo Klimt» abandonó la asociación tras una escisión.",
         now:"El pabellón de exposiciones de la Secesión está abierto, y el Friso de Beethoven se puede ver en su interior."},
        {title:"El Café Museum", short:"Café Museum", place:"Café Museum",
         voice:"Por la noche, el Café Museum. Loos lo hizo severo y desnudo, sin un solo adorno; los bromistas lo llaman «Café Nihilismo». Loos no soporta el ornamento, y yo vivo de él. Pero el café es bueno, y aquí están todos los amigos.",
         src:"Reconstrucción",
         fact:"El café abrió en 1899 con un interior de Adolf Loos. Entre sus clientes habituales se cuentan Klimt, Egon Schiele, Oskar Kokoschka y el propio Loos.",
         now:"El café sigue abierto, a dos minutos de la Secesión."},
        {title:"Las obras de la Kunstschau", short:"Kunstschau", place:"Konzerthaus de Viena, donde estuvo la exposición de 1908",
         voice:"Para terminar, voy a ver las obras. Hoffmann levanta los pabellones de nuestra Kunstschau: cincuenta y cuatro salas. Es nuestra gran declaración, todo lo que sabemos hacer, del cartel al jardín. A ver qué dice Viena.",
         src:"Reconstrucción",
         fact:"La Kunstschau abrió el 1 de junio de 1908 en el solar donde más tarde se construyó el Konzerthaus. En la sala de Klimt colgaba Los amantes, hoy conocido como El beso. El Estado lo compró durante la exposición para la Galería Moderna; hoy está en el Belvedere.",
         now:"El Konzerthaus se inauguró en 1913. El beso cuelga en el Belvedere Superior, a unos 20 minutos a pie hacia el sur."}
      ]
    },
    freud: {
      short:"Freud", name:"Sigmund Freud", inVienna:"en Viena de 1860 a 1938",
      date:"Un miércoles de 1907", dayTitle:"La consulta, el Ring y la tertulia de los miércoles",
      lede:"Freud tiene cincuenta y un años. La interpretación de los sueños salió hace siete años y se vende despacio, sus colegas vieneses se burlan, pero a su alrededor ya se ha formado un círculo de discípulos. Cada miércoles por la noche, en su piso de la Berggasse, se discute sobre el inconsciente.",
      start:"Tranvía D hasta Schlickgasse o U2 hasta Schottentor, y desde allí 5 minutos a pie.",
      epilogue:"Freud murió en Londres el 23 de septiembre de 1939. Cuatro de sus hermanas, que se habían quedado en Viena, fueron asesinadas en el Holocausto.",
      stops:[
        {title:"Berggasse 19", short:"Berggasse 19", place:"Museo Sigmund Freud",
         voice:"Las siete de la mañana. Cada día viene el barbero a arreglarme la barba. Desayuno, periódico, y a las ocho el primer paciente. El diván junto a la pared; yo me siento detrás de la cabecera para que el paciente no me vea. Dice todo lo que le viene a la mente, aunque le parezca trivial o indecoroso. Yo escucho. Ese es mi trabajo.",
         src:"Reconstrucción a partir de la biografía de Ernest Jones y las memorias de Martin Freud",
         fact:"Freud vivió y pasó consulta en esta casa durante 47 años, de 1891 a junio de 1938. Su rutina apenas cambiaba: pacientes de ocho a doce, comida a la una en punto, paseo, de nuevo pacientes de tres a nueve de la noche y, después de cenar, el escritorio, a menudo hasta la una de la madrugada.",
         now:"El Museo Sigmund Freud: sala de espera, consulta y vivienda privada. El famoso diván le acompañó al exilio y hoy está en Londres, en el Freud Museum."},
        {title:"A paso ligero por el Ring", short:"Schottentor", place:"Schottentor y Votivkirche",
         voice:"Después de comer salgo al Ring. Mi hijo dice que no es un paseo sino una marcha: ando a una velocidad tremenda. Por el camino, el estanco. Veinte puros al día; los médicos lo desaprueban. Pero al puro le debo un gran aumento de mi capacidad de trabajo y un mayor dominio de mí mismo.",
         src:"Las palabras sobre la «marcha» son de Martin Freud; la frase sobre el puro recoge las propias palabras de Freud",
         fact:"El Ring, de unos 5 km, se trazó donde estaban las murallas derribadas; se construyó durante toda la infancia y la juventud de Freud. Casi a diario lo recorría a paso vivo, comprando puros y llevando galeradas a su editor.",
         now:"La Votivkirche se consagró en 1879. Desde aquí, siga el Ring hacia el sur hasta la universidad."},
        {title:"La universidad", short:"Universidad", place:"Edificio principal de la Universidad de Viena",
         voice:"La universidad. De joven paseaba por el patio de arcadas entre los bustos de profesores célebres e imaginaba allí mi propio busto, con un verso de Edipo rey: el que resolvió el famoso enigma y fue el más poderoso de los hombres. El año pasado mis discípulos me regalaron por mis cincuenta años un medallón con ese mismo verso. Me quedé pálido, como si hubiera visto un fantasma.",
         src:"Según la biografía de Ernest Jones",
         fact:"Freud fue profesor adjunto (Privatdozent) en 1885, pero catedrático solo en 1902, diecisiete años después. En 1955 se colocó en el patio de arcadas su busto con ese verso de Sófocles. Para el techo del aula magna de la universidad, Gustav Klimt pintó los «cuadros de las facultades»; La Filosofía (1900) y La Medicina (1901) provocaron un enorme escándalo.",
         now:"El patio de arcadas está abierto a los visitantes; el busto de Freud está entre los de los profesores."},
        {title:"El Café Landtmann", short:"Landtmann", place:"Café Landtmann, en el palacio Lieben-Auspitz",
         voice:"Por delante del Burgtheater, por delante del Café Landtmann. Hoy no hay tiempo para un café: a las tres vuelven los pacientes. En cambio, el sábado por la noche habrá tarot con los amigos, y a las cartas nunca tengo prisa.",
         src:"Reconstrucción",
         fact:"El Café Landtmann abrió en 1873 y cuenta a Freud entre sus clientes célebres. El tarock, el juego de cartas vienés, fue durante muchos años el pasatiempo fijo de los sábados de Freud.",
         now:"El café está abierto. Enfrente, el Ayuntamiento; al lado, el Burgtheater."},
        {title:"La Sühnhaus, la «casa de la expiación»", short:"Sühnhaus", place:"Lugar de la Sühnhaus en el Schottenring, entre Heßgasse y Maria-Theresien-Straße",
         voice:"De vuelta, la Sühnhaus, la casa de la expiación. El emperador la mandó construir donde estaba el Ringtheater, en el que en diciembre de 1881 murieron cientos de espectadores en un incendio. Martha y yo nos instalamos aquí después de la boda. Nuestra Mathilde fue la primera niña nacida en esta casa, y el emperador nos felicitó por su nacimiento.",
         src:"Según la biografía de Ernest Jones",
         fact:"Los Freud vivieron en la Sühnhaus de 1886 a 1891; aquí nacieron sus tres hijos mayores. El edificio quedó muy dañado en 1945 y fue derribado en 1951. El actual edificio de la policía es de 1969–1971.",
         now:"En la fachada del edificio de la policía, una placa de 1982 recuerda a las víctimas del incendio del Ringtheater y la Sühnhaus. Hasta la Berggasse hay unos 7 minutos a pie."},
        {title:"Miércoles por la noche", short:"Berggasse 19", place:"La sala de espera de Berggasse 19",
         voice:"Pacientes hasta las nueve, luego la cena. Y hoy es miércoles: en la sala de espera se reúnen los colegas. Café solo, pasteles, puros. El orden de los oradores se sortea con papeletas de una urna, y todos deben hablar. Cuando se hayan ido todos, me sentaré al escritorio. La una de la madrugada aún queda lejos.",
         src:"Reconstrucción a partir de las memorias de miembros de la Sociedad Psicológica de los Miércoles",
         fact:"La Sociedad Psicológica de los Miércoles se reunió en este piso desde 1902; en 1908 se convirtió en la Sociedad Psicoanalítica de Viena. En junio de 1938, tras el Anschluss, Freud, con 82 años, emigró con su familia a Londres. En diciembre de 1938 la BBC grabó su voz: la única grabación conocida de Freud.",
         now:"La sala de espera donde se celebraban las reuniones conserva sus muebles originales: Anna Freud los devolvió al museo."}
      ]
    }
  },
  upcoming: {
    strauss:{short:"Strauss", name:"Johann Strauss hijo", teaser:"Praterstraße 54: el piso donde en 1867 nació el vals El bello Danubio azul."},
    elssler:{short:"Elssler", name:"Fanny Elssler", teaser:"La niña de Gumpendorf, su debut en el Kärntnertortheater y después París, Londres y una gira por América."},
    mahler:{short:"Mahler", name:"Gustav Mahler", teaser:"Diez años al frente de la Ópera de la Corte: apagaba las luces de la sala y no dejaba entrar a los que llegaban tarde."},
    lamarr:{short:"Lamarr", name:"Hedy Lamarr", teaser:"Nacida en Viena, fue estrella de Hollywood y patentó el salto de frecuencia."},
    welles:{short:"Welles", name:"Orson Welles", teaser:"Unos días del otoño de 1948 en el rodaje de El tercer hombre: la noria, las alcantarillas, la Josefsplatz."}
  },
  links: [
    {title:"El espíritu de Mozart de manos de Haydn", text:"Un año después de la muerte de Mozart, Beethoven deja Bonn por Viena. El conde Waldstein le escribe en su álbum: «Con trabajo incesante recibirá usted el espíritu de Mozart de manos de Haydn»."},
    {title:"Escándalo en el techo", text:"Klimt expone La Filosofía, el primero de sus cuadros para el techo de la universidad, y estalla el escándalo. Pocos meses antes había salido La interpretación de los sueños de Freud, con la fecha 1900 en la portada."},
    {title:"El Friso de Beethoven", text:"Klimt pinta el friso sobre la Novena Sinfonía para la exposición de la Secesión dedicada a Beethoven. En la inauguración suena un fragmento de la sinfonía en un arreglo de Gustav Mahler."}
  ],
  how: [
    ["Navegación","Geozonas en lugar de botones","Empieza el paseo y la aplicación sigue tu ubicación. Al acercarte a un lugar, la voz del personaje empieza sola; entre parada y parada ves la distancia a la siguiente."],
    ["Sonido","La voz del personaje","Los monólogos proceden de cartas, diarios y memorias. Por ahora los lee la síntesis de voz del teléfono; después llegarán las grabaciones de actores y, para Freud, la auténtica grabación de la BBC de 1938."],
    ["Inmersión","Momentos en el lugar","Breves escenas sonoras: el oído de Beethoven en 1802 ya está aquí. Después, el ensayo de Fígaro y la fachada del Burgtheater derribado superpuesta a la Michaelerplatz actual."],
    ["Fuentes","Documento o reconstrucción","Bajo cada monólogo se ve de dónde viene: de una carta, de unas memorias o de una reconstrucción dramatizada. Las notas históricas están separadas de la voz del personaje."],
    ["Idiomas","Seis idiomas, sin conexión","La aplicación habla español, alemán, inglés, francés, italiano y ruso. Tras la primera visita queda guardada en el teléfono y funciona sin datos móviles."],
    ["Formatos","Uno o dos días","Un día corto de 2–3 horas o una ruta de dos días: por ejemplo, Beethoven en Heiligenstadt y la noche del estreno de la Quinta Sinfonía en el Theater an der Wien, el 22 de diciembre de 1808."]
  ]
};
