// Textes français des « Journées viennoises ». Ordre des personnages et des étapes identique à js/data.js.
export default {
  heroes: {
    mozart: {
      short:"Mozart", name:"Wolfgang Amadeus Mozart", inVienna:"à Vienne de 1781 à 1791",
      date:"1er mai 1786", dayTitle:"Le jour de la première des Noces de Figaro",
      lede:"Mozart a trente ans. C’est le pianiste le plus en vogue de Vienne, il habite le plus bel appartement de sa vie, et ce soir le Burgtheater, le théâtre de la cour, donne la première de son nouvel opéra sur un livret de Lorenzo Da Ponte.",
      start:"Métro Stephansplatz (U1, U3), puis 3 minutes à pied jusqu’à la Domgasse.",
      epilogue:"Un an plus tard, Mozart emménagera dans un appartement moins cher. Cinq ans plus tard, le 5 décembre 1791, il mourra au 8 Rauhensteingasse, à cinq minutes de la Domgasse.",
      stops:[
        {title:"L’appartement de la Domgasse", short:"Domgasse 5", place:"Mozarthaus Vienna",
         voice:"Bonjour ! Vous êtes dans le plus bel appartement que j’aie jamais loué : quatre pièces, deux cabinets et une cuisine, quatre cent soixante florins par an. Mon père trouve cela insensé. C’est ici que j’ai achevé Figaro. L’hiver dernier, on a joué mes quatuors dans ces pièces, et Monsieur Haydn a dit à mon père que j’étais le plus grand compositeur qu’il connaisse, en personne ou de nom. Cela ne s’oublie pas. Et maintenant une partie de billard, puis en ville.",
         src:"Reconstitution. Les mots de Haydn sont rapportés par Leopold Mozart dans une lettre à sa fille, 16 février 1785",
         fact:"Mozart vécut ici de l’automne 1784 au printemps 1787, plus longtemps que dans aucun autre de ses logements viennois. Il y composa Les Noces de Figaro, plusieurs concertos pour piano et les quatuors dédiés à Haydn. Le billard était sa passion : l’inventaire dressé après sa mort mentionne une table de billard avec ses billes et ses queues.",
         now:"Le musée Mozarthaus Vienna. Des plus de douze appartements viennois de Mozart, c’est le seul qui subsiste."},
        {title:"La cathédrale Saint-Étienne", short:"Stephansdom", place:"Stephansdom",
         voice:"Deux cents pas, et me voici à la cathédrale. C’est ici que j’ai épousé Constanze il y a presque quatre ans, en août. La bénédiction de mon père n’est arrivée que le lendemain. Quand on nous a unis, ma femme et moi nous sommes mis à pleurer, et tout le monde était ému, même le prêtre. J’y repense chaque fois que je passe.",
         src:"D’après la lettre de Mozart à son père, 7 août 1782",
         fact:"Mozart et Constanze Weber se marièrent ici le 4 août 1782. En 1791, Mozart devint adjoint du maître de chapelle de la cathédrale : sans salaire, mais avec le droit de lui succéder. Le 6 décembre 1791, son corps fut béni dans la chapelle du Crucifix, sur le flanc nord de la cathédrale.",
         now:"La descente vers les catacombes part de la chapelle du Crucifix. On peut monter à pied dans la tour sud : 343 marches."},
        {title:"La salle de concert de la Mehlgrube", short:"Mehlgrube", place:"Neuer Markt, à l’emplacement du casino de la Mehlgrube",
         voice:"La Mehlgrube, la « fosse à farine ». Autrefois on y stockait de la farine ; à l’étage, il y a maintenant une salle pour les bals et les concerts. L’hiver dernier, j’y ai donné des concerts le vendredi. Au premier, j’ai joué mon nouveau concerto en ré mineur. Le copiste a livré les parties si tard que je n’ai même pas eu le temps de jouer le rondo en entier : je surveillais moi-même la copie. Mon père était arrivé à Vienne ce jour-là et se trouvait dans la salle.",
         src:"D’après la lettre de Leopold Mozart à sa fille, février 1785",
         fact:"Le 11 février 1785, le Concerto pour piano en ré mineur K. 466 fut joué pour la première fois à la Mehlgrube. Le bâtiment du casino n’existe plus ; l’hôtel Ambassador se dresse à sa place.",
         now:"Au centre de la place, la fontaine de Donner. À trois minutes, le Café Frauenhuber (Himmelpfortgasse 6) : dans cette maison, le 4 mars 1791, Mozart se produisit pour la dernière fois en public comme pianiste."},
        {title:"Le Trattnerhof sur le Graben", short:"Trattnerhof", place:"Trattnerhof",
         voice:"Le Graben, la plus élégante rue de la ville. Il y a deux ans, j’habitais ici, chez l’éditeur Trattner. Sa femme Therese est mon élève ; je lui ai dédié la Fantaisie et la Sonate en ut mineur. Dans la salle de cette maison, j’ai donné des concerts par souscription, et j’avais cent soixante-quatorze souscripteurs : tout le beau monde de Vienne ! J’ai envoyé la liste complète à mon père.",
         src:"D’après la lettre de Mozart à son père, 20 mars 1784",
         fact:"Mozart habita le Trattnerhof de janvier à septembre 1784 et y donna trois concerts par souscription au printemps. Johann Thomas von Trattner était alors le plus grand éditeur et imprimeur de Vienne. L’immeuble actuel date du début du XXe siècle et remplace l’ancien.",
         now:"Tout près, la colonne de la Peste, consacrée en 1693 : Mozart la voyait chaque jour. À deux minutes, le Café Hawelka dans la Dorotheergasse."},
        {title:"Les éditions Artaria", short:"Artaria", place:"Kohlmarkt",
         voice:"Le Kohlmarkt, la boutique Artaria. L’automne dernier, ils ont imprimé mes six quatuors avec une dédicace à Monsieur Haydn. Je lui ai écrit que je confiais à sa protection mes six enfants, fruit d’un long et laborieux travail. Voyons comment ils se vendent. Ensuite, au théâtre : le soir n’est plus très loin.",
         src:"La citation provient de la dédicace italienne des quatuors à Haydn, 1er septembre 1785",
         fact:"Artaria & Comp. était le principal éditeur de musique de Vienne à la fin du XVIIIe siècle : on y publiait Mozart, Haydn et plus tard Beethoven. L’actuelle maison Artaria, au 9 Kohlmarkt, fut construite par Max Fabiani en 1900–1902 ; ce fut la première maison viennoise à façade de marbre.",
         now:"En route vers la place, la confiserie Demel (Kohlmarkt 14). Son histoire commença la même année, en 1786, quand le confiseur Ludwig Dehne ouvrit une boutique sur la Michaelerplatz, face à l’entrée des artistes du Burgtheater."},
        {title:"Première au Burgtheater", short:"Burgtheater", place:"Michaelerplatz, emplacement de l’ancien Burgtheater",
         voice:"Le voici, le Burgtheater, le théâtre de la cour, à deux pas des appartements de l’empereur. À la générale, Benucci a chanté « Non più andrai » avec tant de feu que je répétais à mi-voix : « Bravo, bravo, Benucci ! » Puis les chanteurs et tout l’orchestre ont crié : « Bravo, Maestro ! Viva, viva, grande Mozart ! », et les violonistes frappaient leurs pupitres avec leurs archets. Ce soir, je dirige moi-même l’orchestre depuis le clavier. Souhaitez-moi bonne chance.",
         src:"D’après les souvenirs du ténor Michael Kelly, premier Don Basilio (1826)",
         fact:"La première des Noces de Figaro eut lieu le 1er mai 1786 ; Mozart dirigea lui-même les deux premières représentations. On réclamait tant de bis qu’après la troisième Joseph II interdit de reprendre les numéros à plusieurs voix. Kelly se souvenait de Mozart à la répétition, en pelisse cramoisie et tricorne galonné d’or. L’ancien Burgtheater fut démoli en 1888, lorsque le nouveau théâtre du Ring ouvrit ses portes.",
         now:"À l’emplacement du théâtre se dresse l’aile Michaelertrakt de la Hofburg avec la porte Saint-Michel. Au milieu de la place, des fouilles laissent voir des vestiges romains et médiévaux. Les Noces de Figaro sont régulièrement à l’affiche de l’Opéra d’État de Vienne, à dix minutes d’ici."}
      ]
    },
    beethoven: {
      short:"Beethoven", name:"Ludwig van Beethoven", inVienna:"à Vienne de 1792 jusqu’à sa mort",
      date:"6 octobre 1802", dayTitle:"Heiligenstadt : le jour du Testament",
      lede:"Beethoven a trente et un ans. Vienne le connaît comme le meilleur improvisateur au piano, mais depuis plusieurs années il perd l’ouïe et le cache à tous. Sur le conseil de son médecin, il a passé l’été dans le village viticole de Heiligenstadt. Aujourd’hui, il écrira à ses frères une lettre qu’on ne retrouvera qu’après sa mort.",
      start:"Environ 20 minutes à pied depuis la station U4 Heiligenstadt.",
      epilogue:"Beethoven vivra encore vingt-cinq ans et écrira la Neuvième Symphonie alors qu’il sera complètement sourd. Il mourut à Vienne le 26 mars 1827.",
      stops:[
        {title:"La maison de Heiligenstadt", short:"Probusgasse 6", place:"Musée Beethoven (Wien Museum)",
         voice:"Ici, c’est calme. Trop calme, et ce n’est pas le village. Le docteur Schmidt m’a ordonné de ménager mon ouïe, et j’ai obéi : depuis six mois, je ne parle presque à personne. Les gens me croient orgueilleux et misanthrope. Et je ne peux pas leur dire : parlez plus fort, criez, car je suis sourd. Comment avouer la faiblesse d’un sens qui devrait être chez moi plus parfait que chez les autres ?",
         src:"D’après le Testament de Heiligenstadt, 6 octobre 1802",
         fact:"Du printemps à octobre 1802, Beethoven loua ici un logement sur le conseil de son médecin, Johann Adam Schmidt. Le 6 octobre, il écrivit à ses frères Carl et Johann la lettre connue sous le nom de Testament de Heiligenstadt, et ajouta un post-scriptum le 10 octobre. Elle ne fut jamais envoyée : on la retrouva dans ses papiers après sa mort, en 1827.",
         now:"Le musée Beethoven, antenne du Wien Museum, dans la maison où il vécut en 1802. L’original du Testament est conservé à Hambourg, à la Bibliothèque d’État et universitaire."},
        {title:"La place de l’église Saint-Jacques", short:"Pfarrplatz", place:"Pfarrplatz et église St. Jakob",
         voice:"Octobre, le village fait les vendanges. Je salue les voisins d’un signe de tête et je passe : chaque conversation est une torture. Mes oreilles bourdonnent et grondent jour et nuit. J’ai écrit à mon ami de Bonn : au théâtre, je dois m’asseoir tout près de l’orchestre pour comprendre les acteurs, et de loin je n’entends plus du tout les aigus des instruments et des voix.",
         src:"D’après la lettre de Beethoven à Franz Wegeler, 29 juin 1801",
         fact:"La lettre à son ami d’enfance Wegeler est le premier aveu connu de sa surdité : « depuis presque deux ans, j’évite toute compagnie, parce qu’il m’est impossible de dire aux gens : je suis sourd. » Beethoven habita plus tard la maison du 2 Pfarrplatz, à l’été 1817.",
         now:"Au no 2, un domaine viticole et le Heuriger Mayer am Pfarrplatz : on y boit le vin nouveau là où Beethoven passa l’été 1817."},
        {title:"Promenade vers les vignes", short:"Eroicagasse", place:"Eroicagasse, en direction du Beethovengang",
         voice:"Je traverse les champs avec Ries, mon élève. Soudain, il s’arrête : « Vous entendez ? Un berger joue du pipeau. » J’écoute, longtemps, et rien. Ries dit qu’il n’entend plus rien lui non plus, mais je vois qu’il le dit par pitié. Quelle humiliation. De tels moments m’ont mené près du désespoir ; peu s’en fallut que je ne mette fin à mes jours.",
         src:"D’après les souvenirs de Ferdinand Ries (1838) et le texte du Testament",
         fact:"La scène a été racontée par Ferdinand Ries : un berger jouait du pipeau, Beethoven n’entendit rien pendant une demi-heure et devint ensuite extrêmement silencieux et sombre. Les historiens admettent que Ries, qui écrivait des décennies plus tard, a pu mêler son souvenir au texte du Testament, où Beethoven décrit la même scène avec ses propres mots.",
         now:"L’Eroicagasse monte vers le chemin Beethovengang. Elle porte le nom de la Troisième Symphonie, l’« Eroica » ; à l’été 1803, Beethoven y travailla dans la maison du 92 Döblinger Hauptstraße."},
        {title:"Le chemin le long du ruisseau", short:"Beethovengang", place:"Beethovengang, monument « Beethovenruhe »",
         voice:"Je descends au ruisseau. Ici, je n’ai rien à expliquer à personne ; les arbres ne demandent pas qu’on les entende. Personne ne peut aimer la campagne autant que moi. Car les forêts, les arbres, les rochers renvoient l’écho que l’homme désire.",
         src:"Les deux dernières phrases sont tirées de la lettre de Beethoven à Therese Malfatti, 1810",
         fact:"Beethoven aimait le chemin qui longe le Schreiberbach. Selon la tradition, c’est ici que naquit plus tard la « Scène au bord du ruisseau » de la Sixième Symphonie, la « Pastorale » (1808) ; l’histoire remonte à son secrétaire Anton Schindler, source pas toujours fiable. En 1863, on inaugura au bord du chemin un buste en bronze d’Anton Dominik Fernkorn, le premier monument à Beethoven des environs de Vienne.",
         now:"Le monument « Beethovenruhe » se dresse au bord du ruisseau, près de la Kahlenberger Straße. D’ici, on peut monter au Kahlenberg par le sentier de randonnée urbain no 1."},
        {title:"La lettre aux frères", short:"Probusgasse 6", place:"De retour dans la maison de la Probusgasse",
         voice:"Ô vous, hommes qui me tenez ou me déclarez haineux, obstiné ou misanthrope, comme vous êtes injustes envers moi ! Vous ne connaissez pas la cause secrète de ce qui vous paraît ainsi. Seul l’art, lui seul, m’a retenu. Ah, il me semblait impossible de quitter le monde avant d’avoir produit tout ce que je me sentais appelé à faire. Heiligenstadt, le 6 octobre 1802.",
         src:"Testament de Heiligenstadt, 6 octobre 1802 (extraits traduits)",
         fact:"Quelques semaines plus tard, Beethoven rentrera à Vienne et commencera la Troisième Symphonie. On fait d’ordinaire commencer avec elle sa période « héroïque » : la Cinquième Symphonie, l’opéra Fidelio, le Concerto pour violon.",
         now:"L’exposition du musée raconte l’histoire du Testament et la manière dont Beethoven vécut avec sa surdité."}
      ]
    },
    klimt: {
      short:"Klimt", name:"Gustav Klimt", inVienna:"a vécu toute sa vie à Vienne",
      date:"Printemps 1908", dayTitle:"Petit-déjeuner au Tivoli, journée à l’atelier",
      lede:"Klimt a quarante-cinq ans. Il y a trois ans, il a quitté avec ses amis la Sécession qu’il avait lui-même fondée. Il prépare maintenant la Kunstschau, une grande exposition dans des pavillons de Josef Hoffmann, où il montrera pour la première fois le tableau qu’on appellera plus tard Le Baiser.",
      start:"Environ 10 minutes à pied depuis la station U3 Zieglergasse.",
      epilogue:"Klimt mourut le 6 février 1918. La même année disparurent Egon Schiele, Otto Wagner et Koloman Moser, et à l’automne l’empire des Habsbourg prit fin.",
      stops:[
        {title:"La maison où il vivait avec sa mère", short:"Westbahnstraße", place:"Immeuble d’habitation à Neubau",
         voice:"Je me lève tôt. Je vis avec ma mère et mes sœurs, il en a toujours été ainsi. Je ne sais pas parler de moi et je n’aime pas cela. Il n’y a rien de particulier à voir en moi. Celui qui veut savoir quelque chose de moi en tant qu’artiste, la seule chose qui compte, n’a qu’à regarder attentivement mes tableaux.",
         src:"D’après le texte de Klimt « Commentaire sur un autoportrait inexistant »",
         fact:"Klimt vécut ici jusqu’à sa mort avec sa mère Anna (morte en 1915) et ses sœurs célibataires Klara et Hermine. Il ne se maria jamais ; la personne la plus proche de lui resta toute sa vie Emilie Flöge.",
         now:"Un immeuble d’habitation avec une plaque commémorative dédiée à Klimt, inaugurée en 2001. Le Tivoli est à environ une heure de marche."},
        {title:"Petit-déjeuner au Tivoli", short:"Tivoli", place:"Ancien établissement du Tivoli à Meidling, entre Hohenbergstraße, Tivoligasse et Grünbergstraße",
         go:"U4 jusqu’à Schönbrunn ou Meidling Hauptstraße, puis environ 15 minutes de montée à pied. Klimt y allait à pied ou prenait le Stadtbahn, sur la même ligne que l’actuelle U4.",
         voice:"Chaque matin, je marche jusqu’au Tivoli, près du parc de Schönbrunn. Parfois, je prends le nouveau chemin de fer urbain jusqu’à la station Schönbrunn. Ici, tout est comme dans la vieille Vienne, et cela me plaît. Le petit-déjeuner doit être copieux, avec de la crème fouettée : jusqu’au soir, tant que je travaille, je ne mange presque rien.",
         src:"Reconstitution d’après les souvenirs de contemporains",
         fact:"L’établissement de plaisance et laiterie du Tivoli, sur le Grüner Berg, était l’un des lieux préférés de Klimt ; Egon Schiele y venait aussi. Un petit-déjeuner copieux avec une grosse portion de crème fouettée faisait partie de son rituel quotidien. La station Schönbrunn, comme tout le Stadtbahn, fut conçue par Otto Wagner.",
         now:"Le bâtiment principal du Tivoli brûla en 1980 et fut démoli ; des ensembles d’habitation l’ont remplacé, dont la cité protégée « Am Tivoli ». Tout près, le parc de Schönbrunn et le café de la Gloriette, avec vue sur la ville."},
        {title:"L’atelier au jardin", short:"Atelier", place:"Cour d’un immeuble de la Josefstädter Straße",
         go:"Environ 35 minutes en transports ; pour la fin du trajet, prenez le tram 2, qui passe directement par la Josefstädter Straße.",
         voice:"L’atelier est au fond de la cour, dans le jardin. Des chats, le silence, ma blouse bleue. Les modèles arrivent le matin et attendent des heures que je me mette au travail. Sur le chevalet, un grand tableau carré : deux êtres sur une prairie en fleurs, de l’or et de l’argent. Je ne sais pas encore comment l’appeler.",
         src:"Reconstitution",
         fact:"Klimt travailla ici de 1892 à 1911, dans un pavillon de jardin au fond de la cour d’une maison de 1709. Dans cet atelier, il peignit le Portrait d’Adele Bloch-Bauer I et Le Baiser (1907–1908). Il s’installa ensuite dans un atelier à Hietzing, au 11 Feldmühlgasse.",
         now:"Une cour d’immeuble dans la Josefstadt. Le dernier atelier de Klimt se visite : c’est aujourd’hui le musée Klimt Villa, à Hietzing."},
        {title:"Le salon des sœurs Flöge", short:"Casa Piccola", place:"Maison Casa Piccola, face au MuseumsQuartier",
         voice:"Je passe voir Emilie. Son salon de mode a été aménagé par la Wiener Werkstätte : du blanc et du noir, pas une fioriture de trop. Les robes y sont amples, sans corset, comme sur mes tableaux. Cet été, nous repartirons au bord de l’Attersee avec la famille Flöge. En attendant, je lui écris des cartes postales, parfois plusieurs par jour.",
         src:"Reconstitution. Quelque 400 cartes et lettres de Klimt à Emilie Flöge ont été conservées",
         fact:"Le salon « Schwestern Flöge » d’Emilie et de ses sœurs Helene et Pauline occupa cette maison de 1904 à 1938 ; l’intérieur fut conçu par Josef Hoffmann et Koloman Moser. Klimt photographiait Emilie dans des robes « réformées » amples ; certains modèles furent peut-être imaginés à deux.",
         now:"La maison à la tourelle pointue sur la Mariahilfer Straße, face à l’entrée latérale du MuseumsQuartier. Le salon n’existe plus."},
        {title:"Le pavillon de la Sécession", short:"Sécession", place:"Secession",
         voice:"Je ne passe jamais devant la Sécession sans émotion. Au-dessus de l’entrée, un feuillage d’or et la devise : « À chaque époque son art, à l’art sa liberté. » Nous avons bâti cette maison comme un temple de l’art nouveau. En 1902, j’y ai peint une frise sur la Neuvième Symphonie de Beethoven. Et en 1905, je suis parti avec mes amis.",
         src:"Reconstitution. La devise au-dessus de l’entrée est du critique Ludwig Hevesi",
         fact:"Le bâtiment fut construit par Joseph Maria Olbrich en 1898. Klimt créa la Frise Beethoven pour la 14e exposition de la Sécession en 1902 ; on la voit aujourd’hui au sous-sol. En 1905, le « groupe Klimt » quitta l’association après une scission.",
         now:"Le pavillon d’exposition de la Sécession est ouvert, et la Frise Beethoven est visible à l’intérieur."},
        {title:"Le Café Museum", short:"Café Museum", place:"Café Museum",
         voice:"Le soir, le Café Museum. Loos l’a voulu sévère et nu, sans un seul ornement ; les plaisantins l’appellent le « Café Nihilisme ». Loos ne supporte pas l’ornement, et moi, j’en vis. Mais le café y est bon, et tous les amis sont là.",
         src:"Reconstitution",
         fact:"Le café ouvrit en 1899 dans un décor d’Adolf Loos. On compte parmi ses habitués Klimt, Egon Schiele, Oskar Kokoschka et Loos lui-même.",
         now:"Le café est toujours ouvert, à deux minutes de la Sécession."},
        {title:"Le chantier de la Kunstschau", short:"Kunstschau", place:"Konzerthaus de Vienne, à l’emplacement de l’exposition de 1908",
         voice:"Pour finir, je vais voir le chantier. Hoffmann construit les pavillons de notre Kunstschau : cinquante-quatre salles. C’est notre grande déclaration, tout ce que nous savons faire, de l’affiche au jardin. Voyons ce qu’en dira Vienne.",
         src:"Reconstitution",
         fact:"La Kunstschau ouvrit le 1er juin 1908 sur le terrain où l’on bâtit plus tard le Konzerthaus. Dans la salle Klimt était accroché Les Amoureux, connu aujourd’hui sous le nom de Le Baiser. L’État l’acheta pendant l’exposition pour la Galerie moderne ; il est aujourd’hui au Belvédère.",
         now:"Le Konzerthaus a ouvert en 1913. Le Baiser est exposé au Belvédère supérieur, à environ 20 minutes à pied vers le sud."}
      ]
    },
    freud: {
      short:"Freud", name:"Sigmund Freud", inVienna:"à Vienne de 1860 à 1938",
      date:"Un mercredi de 1907", dayTitle:"Le cabinet, le Ring et la société du mercredi",
      lede:"Freud a cinquante et un ans. L’Interprétation du rêve est parue il y a sept ans et se vend lentement, ses collègues viennois ricanent, mais un cercle de disciples s’est déjà formé autour de lui. Chaque mercredi soir, on débat de l’inconscient dans son appartement de la Berggasse.",
      start:"Tram D jusqu’à Schlickgasse ou U2 jusqu’à Schottentor, puis 5 minutes à pied.",
      epilogue:"Freud mourut à Londres le 23 septembre 1939. Quatre de ses sœurs, restées à Vienne, furent assassinées pendant la Shoah.",
      stops:[
        {title:"19 Berggasse", short:"Berggasse 19", place:"Musée Sigmund Freud",
         voice:"Sept heures du matin. Chaque jour, le barbier vient me tailler la barbe. Petit-déjeuner, journal, et à huit heures le premier patient. Le divan contre le mur ; je m’assieds derrière sa tête pour que le patient ne me voie pas. Il dit tout ce qui lui passe par l’esprit, même si cela lui paraît insignifiant ou inconvenant. J’écoute. C’est mon travail.",
         src:"Reconstitution d’après la biographie d’Ernest Jones et les souvenirs de Martin Freud",
         fact:"Freud vécut et reçut ses patients dans cette maison pendant 47 ans, de 1891 à juin 1938. Son emploi du temps changeait à peine : patients de huit heures à midi, déjeuner à une heure précise, promenade, de nouveau des patients de trois à neuf heures du soir, puis, après le dîner, le bureau, souvent jusqu’à une heure du matin.",
         now:"Le musée Sigmund Freud : salle d’attente, cabinet et appartement privé. Le célèbre divan l’a suivi en exil et se trouve aujourd’hui à Londres, au Freud Museum."},
        {title:"Tour du Ring au pas de charge", short:"Schottentor", place:"Schottentor et Votivkirche",
         voice:"Après le déjeuner, je sors sur le Ring. Mon fils dit que ce n’est pas une promenade mais une marche forcée : je vais à une vitesse terrible. En chemin, le bureau de tabac. Vingt cigares par jour, les médecins désapprouvent. Mais je dois au cigare un grand accroissement de ma capacité de travail et une plus grande maîtrise de moi-même.",
         src:"Les mots sur la « marche » sont de Martin Freud ; la phrase sur le cigare reprend les propres mots de Freud",
         fact:"Le Ring, long d’environ 5 km, fut tracé à l’emplacement des remparts démolis ; il se construisit pendant toute l’enfance et la jeunesse de Freud. Presque chaque jour, il en faisait le tour d’un pas vif, achetant des cigares et portant des épreuves à son éditeur.",
         now:"La Votivkirche fut consacrée en 1879. D’ici, suivez le Ring vers le sud, jusqu’à l’université."},
        {title:"L’université", short:"Université", place:"Bâtiment principal de l’université de Vienne",
         voice:"L’université. Jeune homme, je me promenais dans la cour à arcades parmi les bustes de professeurs célèbres et j’y imaginais mon propre buste, avec un vers d’Œdipe roi : celui qui résolut la fameuse énigme et fut un homme très puissant. L’an dernier, pour mes cinquante ans, mes disciples m’ont offert un médaillon portant ce vers-là. J’ai pâli, comme si j’avais vu un fantôme.",
         src:"D’après la biographie d’Ernest Jones",
         fact:"Freud devint privat-docent en 1885, mais professeur seulement en 1902, dix-sept ans plus tard. En 1955, son buste portant ce vers de Sophocle fut installé dans la cour à arcades. Pour le plafond de la grande salle de l’université, Gustav Klimt peignit les « tableaux des facultés » ; La Philosophie (1900) et La Médecine (1901) firent un énorme scandale.",
         now:"La cour à arcades est ouverte aux visiteurs ; le buste de Freud se dresse parmi ceux des professeurs."},
        {title:"Le Café Landtmann", short:"Landtmann", place:"Café Landtmann, au palais Lieben-Auspitz",
         voice:"Devant le Burgtheater, devant le Café Landtmann. Pas le temps de prendre un café aujourd’hui : à trois heures, les patients reviennent. Mais samedi soir, il y aura le tarot avec les amis, et aux cartes je ne suis jamais pressé.",
         src:"Reconstitution",
         fact:"Le Café Landtmann ouvrit en 1873 et compte Freud parmi ses hôtes célèbres. Le tarot viennois fut pendant de longues années le passe-temps du samedi de Freud.",
         now:"Le café est ouvert. En face, l’hôtel de ville ; à côté, le Burgtheater."},
        {title:"La Sühnhaus, la « maison de l’expiation »", short:"Sühnhaus", place:"Emplacement de la Sühnhaus sur le Schottenring, entre Heßgasse et Maria-Theresien-Straße",
         voice:"Sur le chemin du retour, la Sühnhaus, la maison de l’expiation. L’empereur l’a fait bâtir à l’emplacement du Ringtheater, où des centaines de spectateurs périrent dans un incendie en décembre 1881. Martha et moi nous y sommes installés après notre mariage. Notre Mathilde a été le premier enfant né dans cette maison, et l’empereur nous a félicités pour sa naissance.",
         src:"D’après la biographie d’Ernest Jones",
         fact:"Les Freud habitèrent la Sühnhaus de 1886 à 1891 ; leurs trois aînés y naquirent. L’immeuble, gravement endommagé en 1945, fut démoli en 1951. L’actuel bâtiment de la police date de 1969–1971.",
         now:"Sur la façade du bâtiment de la police, une plaque de 1982 rappelle les victimes de l’incendie du Ringtheater et la Sühnhaus. La Berggasse est à environ 7 minutes à pied."},
        {title:"Le mercredi soir", short:"Berggasse 19", place:"La salle d’attente du 19 Berggasse",
         voice:"Des patients jusqu’à neuf heures, puis le dîner. Et c’est mercredi : les collègues se réunissent dans la salle d’attente. Café noir, gâteaux, cigares. L’ordre des orateurs est tiré au sort dans une urne, et chacun doit prendre la parole. Quand tous seront partis, je m’assiérai à mon bureau. Une heure du matin, c’est encore loin.",
         src:"Reconstitution d’après les souvenirs de membres de la Société psychologique du mercredi",
         fact:"La Société psychologique du mercredi se réunit dans cet appartement à partir de 1902 ; en 1908, elle devint la Société psychanalytique de Vienne. En juin 1938, après l’Anschluss, Freud, âgé de 82 ans, émigra avec sa famille à Londres. En décembre 1938, la BBC enregistra sa voix : le seul enregistrement connu de Freud.",
         now:"La salle d’attente où se tenaient les réunions a conservé son mobilier d’origine : Anna Freud l’a rendu au musée."}
      ]
    }
  },
  upcoming: {
    strauss:{short:"Strauss", name:"Johann Strauss fils", teaser:"Praterstraße 54 : l’appartement où fut composée en 1867 la valse Le Beau Danube bleu."},
    elssler:{short:"Elssler", name:"Fanny Elssler", teaser:"La petite fille de Gumpendorf, ses débuts au Kärntnertortheater, puis Paris, Londres et une tournée en Amérique."},
    mahler:{short:"Mahler", name:"Gustav Mahler", teaser:"Dix ans à la tête de l’Opéra de la cour : il fit éteindre la salle et refusa l’entrée aux retardataires."},
    lamarr:{short:"Lamarr", name:"Hedy Lamarr", teaser:"Née à Vienne, elle devint une star d’Hollywood et breveta l’étalement de spectre par saut de fréquence."},
    welles:{short:"Welles", name:"Orson Welles", teaser:"Quelques jours de l’automne 1948 sur le tournage du Troisième Homme : la grande roue, les égouts, la Josefsplatz."}
  },
  links: [
    {title:"L’esprit de Mozart des mains de Haydn", text:"Un an après la mort de Mozart, Beethoven quitte Bonn pour Vienne. Le comte Waldstein écrit dans son album : « Par un travail assidu, vous recevrez l’esprit de Mozart des mains de Haydn. »"},
    {title:"Scandale au plafond", text:"Klimt expose La Philosophie, la première de ses toiles pour le plafond de l’université, et provoque un scandale. Quelques mois plus tôt paraissait L’Interprétation du rêve de Freud, datée de 1900 sur sa page de titre."},
    {title:"La Frise Beethoven", text:"Klimt peint sa frise sur la Neuvième Symphonie pour l’exposition de la Sécession consacrée à Beethoven. À l’inauguration, un passage de la symphonie est joué dans un arrangement de Gustav Mahler."}
  ],
  how: [
    ["Navigation","Des géozones plutôt que des boutons","Lancez la promenade et l’application suit votre position. Quand vous approchez d’un lieu, la voix du personnage démarre d’elle-même ; entre deux étapes, vous voyez la distance jusqu’à la suivante."],
    ["Son","La voix du personnage","Les monologues sont tirés de lettres, de journaux et de souvenirs. Pour l’instant, c’est la synthèse vocale du téléphone qui les lit ; viendront ensuite des enregistrements de comédiens et, pour Freud, le véritable enregistrement de la BBC de 1938."],
    ["Immersion","Des moments sur place","De courtes scènes sonores : l’ouïe de Beethoven en 1802 est déjà là. Ensuite : la répétition de Figaro et la façade du Burgtheater démoli superposée à la Michaelerplatz d’aujourd’hui."],
    ["Sources","Document ou reconstitution","Sous chaque monologue, on voit d’où il vient : d’une lettre, de souvenirs ou d’une reconstitution romancée. Les notes historiques sont séparées de la voix du personnage."],
    ["Langues","Six langues, hors ligne","L’application parle français, allemand, anglais, italien, espagnol et russe. Après la première visite, elle est enregistrée sur le téléphone et fonctionne sans données mobiles."],
    ["Formats","Un ou deux jours","Une courte journée de 2 à 3 heures ou un parcours de deux jours : par exemple Beethoven à Heiligenstadt et le soir de la création de la Cinquième Symphonie au Theater an der Wien, le 22 décembre 1808."]
  ]
};
